<a href="https://colab.research.google.com/github/kartikmeghwal75/CODESOFT/blob/main/my%20project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.pipeline import Pipeline

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'sms-spam-collection-dataset' dataset.
Path to dataset files: /kaggle/input/sms-spam-collection-dataset


In [5]:
import os

df = pd.read_csv(os.path.join(path, "spam.csv"), encoding="latin-1")

print(df.head())

     v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  


In [6]:
df = df[['v1','v2']]

df.columns = ['label','message']

print(df.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


In [7]:
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

print(df.head())

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...


/tmp/ipykernel_4484/1990914758.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df['label'].map({


In [8]:
print(df.info())

print(df.isnull().sum())

print(df['label'].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   int64 
 1   message  5572 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB
None
label      0
message    0
dtype: int64
label
0    4825
1     747
Name: count, dtype: int64


In [9]:
X = df["message"]

y = df["label"]

In [10]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
nb_model = Pipeline([

    ("tfidf",TfidfVectorizer()),

    ("classifier",MultinomialNB())

])

nb_model.fit(X_train,y_train)

pred_nb = nb_model.predict(X_test)

In [12]:
print("Naive Bayes")

print("Accuracy")

print(accuracy_score(y_test,pred_nb))

print(classification_report(y_test,pred_nb))

print(confusion_matrix(y_test,pred_nb))

Naive Bayes
Accuracy
0.9605381165919282
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       1.00      0.70      0.83       149

    accuracy                           0.96      1115
   macro avg       0.98      0.85      0.90      1115
weighted avg       0.96      0.96      0.96      1115

[[966   0]
 [ 44 105]]


In [14]:
lr_model = Pipeline([

    ("tfidf",TfidfVectorizer()),

    ("classifier",LogisticRegression())

])

lr_model.fit(X_train,y_train)

pred_lr = lr_model.predict(X_test)

In [15]:
print("Logistic Regression")

print("Accuracy")

print(accuracy_score(y_test,pred_lr))

print(classification_report(y_test,pred_lr))

print(confusion_matrix(y_test,pred_lr))

Logistic Regression
Accuracy
0.9721973094170404
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       966
           1       0.99      0.80      0.88       149

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115

[[965   1]
 [ 30 119]]


In [17]:
svm_model = Pipeline([

    ("tfidf",TfidfVectorizer()),

    ("classifier",LinearSVC())

])

svm_model.fit(X_train,y_train)

pred_svm = svm_model.predict(X_test)

In [18]:
print("Support Vector Machine")

print("Accuracy")

print(accuracy_score(y_test,pred_svm))

print(classification_report(y_test,pred_svm))

print(confusion_matrix(y_test,pred_svm))

Support Vector Machine
Accuracy
0.9847533632286996
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       0.99      0.90      0.94       149

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115

[[964   2]
 [ 15 134]]


In [19]:
models = {
    "Naive Bayes":nb_model,
    "Logistic Regression":lr_model,
    "Support Vector Machine":svm_model
}

for name,model in models.items():

    pred = model.predict(X_test)

    print("="*40)

    print(name)

    print("Accuracy:",
          accuracy_score(y_test,pred))

Naive Bayes
Accuracy: 0.9605381165919282
Logistic Regression
Accuracy: 0.9721973094170404
Support Vector Machine
Accuracy: 0.9847533632286996


In [25]:
message = [
    "Congratulations! You have won a free iPhone. Click here now."
]

prediction = svm_model.predict(message)

if prediction[0]==1:
    print("Spam Message")
else:
    print("Legitimate Message")

Spam Message


In [29]:
#Example testing

message = [
    "Congratulations! Claim your ₹50,000 cash reward now."
]
prediction = svm_model.predict(message)

if prediction[0]==1:
    print("Spam Message")
else:
    print("Legitimate Message")

Spam Message


In [30]:
message = [
    "Hey, I'll reach home in 10 minutes."
]

prediction = svm_model.predict(message)

if prediction[0]==1:
    print("Spam Message")
else:
    print("Legitimate Message")

Legitimate Message


In [31]:
message = [
    "URGENT! Your account has been suspended. Verify immediately."
]

prediction = svm_model.predict(message)

if prediction[0]==1:
    print("Spam Message")
else:
    print("Legitimate Message")

Spam Message


In [33]:
message = [
    "Happy Birthday! Have a wonderful day."
]

prediction = svm_model.predict(message)

if prediction[0]==1:
    print("Spam Message")
else:
    print("Legitimate Message")

Legitimate Message
