<a href="https://colab.research.google.com/github/kartikmeghwal75/CODESOFT/blob/main/myproject3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

In [7]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shantanudhakadd/bank-customer-churn-prediction")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'bank-customer-churn-prediction' dataset.
Path to dataset files: /kaggle/input/bank-customer-churn-prediction


In [14]:
import os


csv_file_path = os.path.join(path, 'Churn_Modelling.csv')


df = pd.read_csv(csv_file_path)

print(df.head())
print(df.shape)

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [15]:
print(df.info())

print(df.describe())

print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None
         RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  1000

In [16]:
df.drop(["RowNumber","CustomerId","Surname"],axis=1,inplace=True)

In [27]:
df["Churn"] = df["Exited"]

In [28]:
label = LabelEncoder()

categorical = df.select_dtypes(include="object").columns

for col in categorical:
    df[col] = label.fit_transform(df[col])

In [29]:
X = df.drop("Exited",axis=1)

y = df["Exited"]

In [30]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [31]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [32]:
lr = LogisticRegression()

lr.fit(X_train,y_train)

pred_lr = lr.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test,pred_lr))

print(classification_report(y_test,pred_lr))

print(confusion_matrix(y_test,pred_lr))

Accuracy
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1593
           1       1.00      1.00      1.00       407

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

[[1593    0]
 [   0  407]]


In [33]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train,y_train)

pred_rf = rf.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test,pred_rf))

print(classification_report(y_test,pred_rf))

print(confusion_matrix(y_test,pred_rf))

Accuracy
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1593
           1       1.00      1.00      1.00       407

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

[[1593    0]
 [   0  407]]


In [34]:
gb = GradientBoostingClassifier()

gb.fit(X_train,y_train)

pred_gb = gb.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test,pred_gb))

print(classification_report(y_test,pred_gb))

print(confusion_matrix(y_test,pred_gb))

Accuracy
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1593
           1       1.00      1.00      1.00       407

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

[[1593    0]
 [   0  407]]


In [35]:
print("Logistic Regression")

print(roc_auc_score(
    y_test,
    lr.predict_proba(X_test)[:,1]
))

print("Random Forest")

print(roc_auc_score(
    y_test,
    rf.predict_proba(X_test)[:,1]
))

print("Gradient Boosting")

print(roc_auc_score(
    y_test,
    gb.predict_proba(X_test)[:,1]
))

Logistic Regression
1.0
Random Forest
1.0
Gradient Boosting
1.0


In [36]:
models = {
    "Logistic Regression":lr,
    "Random Forest":rf,
    "Gradient Boosting":gb
}

for name,model in models.items():

    pred = model.predict(X_test)

    print("="*40)

    print(name)

    print("Accuracy:",
          accuracy_score(y_test,pred))

Logistic Regression
Accuracy: 1.0
Random Forest
Accuracy: 1.0
Gradient Boosting
Accuracy: 1.0


In [37]:
sample = X_test[0].reshape(1,-1)

prediction = rf.predict(sample)

if prediction[0]==1:
    print("Customer Will Churn")
else:
    print("Customer Will Stay")

Customer Will Stay
